---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: isolate-ns-a
spec:
  # Allow communication only inside the namespace.
  namespaceSelector: projectcalico.org/name == 'ns-a'
  ingress:
  - action: Allow
<<<<<<< HEAD
    #protocol: TCP
    source:
      namespaceSelector: projectcalico.org/name == 'ns-a'
  egress:
  # Allow communication only inside the namespace. 
=======
    source:
      namespaceSelector: projectcalico.org/name == 'ns-a'
  egress:
  # Allow communication only inside the namespace.
>>>>>>> 681ca99259a834c431d31e8b4864c59b147787e7
  # No internet access.
  - action: Allow
    destination:
      namespaceSelector: projectcalico.org/name == 'ns-a'
  # Allow access to CoreDNS pods in kube-system namespace.
  - action: Allow
    protocol: TCP
    destination:
<<<<<<< HEAD
      selector: k8s-app == "kube-dns" 
=======
      selector: k8s-app == "kube-dns"
>>>>>>> 681ca99259a834c431d31e8b4864c59b147787e7
      namespaceSelector: projectcalico.org/name == 'kube-system'
      ports:
      - 53
  - action: Allow
    protocol: UDP
    destination:
      selector: k8s-app == "kube-dns"
      namespaceSelector: projectcalico.org/name == 'kube-system'
      ports:
      - 53
  # Allow access to the kube-api server from kubernetes service in the default namespace. Used by operator and controller.
  - action: Allow
    destination:
      services:
        name: kubernetes
<<<<<<< HEAD
        namespace: default
=======
        namespace: default
>>>>>>> 681ca99259a834c431d31e8b4864c59b147787e7
