---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
spec:
  containers:
    - name: test-pvc
      image: debian
      command:
      - "/bin/sh"
      - "-c"
      - "sleep 3600"
      volumeMounts:
      - mountPath: "/data"
        name: data-pvc
  volumes:
    - name: data-pvc
      persistentVolumeClaim:
        claimName: data-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
<<<<<<< HEAD
      storage: 100Gi
=======
      storage: 100Gi
>>>>>>> 681ca99259a834c431d31e8b4864c59b147787e7
